In [1]:
import numpy as np
import scipy.ndimage as spndim
import pandas as pd
import matplotlib.colors as clr
import matplotlib.pyplot as plt
import matplotlib.cm as mcm
import matplotlib.colorbar as mcb
import matplotlib.ticker as mtk
import utils.engine as ue
import utils.visualizer as uv

In [2]:
%load_ext autoreload
%autoreload 2

In [ ]:
# with open("Validation/SHEBA_Data/01-forcing.dat") as file:
#     arr = file.readlines()
    
# cols_1 = [colname.replace('\n', '') for colname in arr[0].split(" ") if colname]
# file_1 = np.array([[float(el) for el in line.split(" ") if el] for line in arr[1:]])

In [ ]:
# with open("Validation/SHEBA_Data/02-hs-hi_thickness.dat") as file:
#     arr = file.readlines()
    
# cols_2 = [colname.replace('\n', '') for colname in arr[0].split(" ") if colname]
# file_2 = np.array([[float(el) for el in line.split(" ") if el] for line in arr[1:]])

In [ ]:
# with open("Validation/SHEBA_Data/06-depth_pit.dat") as file:
#     arr = file.readlines()
    
# file_6 = np.array([[float(el) for el in line.split(" ") if el] for line in arr])
# file_6[:, 0] = np.round(file_6[:, 0], 4)

In [ ]:
# with open("Validation/SHEBA_Data/07-pit_fcond.dat") as file:
#     arr = file.readlines()
    
# cols_7 = [colname.replace('\n', '') for colname in arr[0].split(" ") if colname]
# file_7 = np.array([[float(el) for el in line.split(" ") if el] for line in arr[1:]])

In [ ]:
# with open("Validation/SHEBA_Data/08-tocn.dat") as file:
#     arr = file.readlines()
    
# file_8 = np.array([[float(el) for el in line.split(" ") if el] for line in arr])

In [ ]:
# with open("Validation/SHEBA_Data/09-focn.dat") as file:
#     arr = file.readlines()
    
# cols_9 = [colname.replace('\n', '') for colname in arr[0].split(" ") if colname]
# file_9 = np.array([[float(el) for el in line.split(" ") if el] for line in arr[1:]])

In [ ]:
# with open("Validation/SHEBA_Data/10-temp.dat") as file:
#     arr = file.readlines()
    
# file_10 = np.array([[float(el) for el in line.split(" ") if el] for line in arr])

In [ ]:
# with open("Validation/SHEBA_Data/11-turbflux.dat") as file:
#     arr = file.readlines()
    
# cols_11 = [colname.replace('\n', '') for colname in arr[0].split(" ") if colname]
# file_11 = np.array([[float(el) for el in line.split(" ") if el] for line in arr[1:]])

In [ ]:
# data = pd.DataFrame(file_1, columns=cols_1)

# data_2 = pd.DataFrame(file_2, columns=cols_2)
# data = data.merge(data_2.iloc[:, 1:],
#                   left_on=(data['jday']*1000).astype('int32'),
#                   right_on=(data_2['jday']*1000).astype('int32')).iloc[:, 1:]

# data_6 = pd.DataFrame(file_6, columns=['jday', 'hs', 'hi', 'hs_level', 'hf_level', 'hi_level'])
# data = data.merge(data_6.iloc[:, 1:],
#                   left_on=(data['jday']*1000).astype('int32'),
#                   right_on=(data_6['jday']*1000).astype('int32')).iloc[:, 1:]

# data_7 = pd.DataFrame(file_7, columns=cols_7)
# data = data.merge(data_7.iloc[:, 1:],
#                   left_on=(data['jday']*1000).astype('int32'),
#                   right_on=(data_7['jday']*1000).astype('int32')).iloc[:, 1:]

# data_8 = pd.DataFrame(file_8, columns=['jday', 'Tocn'])
# data = data.merge(data_8.iloc[:, 1:],
#                   left_on=(data['jday']*1000).astype('int32'),
#                   right_on=(data_8['jday']*1000).astype('int32')).iloc[:, 1:]

# data_9 = pd.DataFrame(file_9, columns=cols_9)
# data = data.merge(data_9.iloc[:, 1:],
#                   left_on=(data['jday']*1000).astype('int32'),
#                   right_on=(data_9['jday']*1000).astype('int32')).iloc[:, 1:]

# data_10 = pd.DataFrame(file_10, columns=['jday'] + ['T_{}'.format(i) for i in range(1, 51)])
# data = data.merge(data_10.iloc[:, 1:],
#                   left_on=(data['jday']*1000).astype('int32'),
#                   right_on=(data_10['jday']*1000).astype('int32')).iloc[:, 1:]

# data_11 = pd.DataFrame(file_11, columns=cols_11)
# data = data.merge(data_11.iloc[:, 1:],
#                   left_on=(data['jday']*1000).astype('int32'),
#                   right_on=(data_11['jday']*1000).astype('int32')).iloc[:, 1:]

In [ ]:
# data.to_csv('Validation/full_data.csv', index=False)

In [15]:
sim_proc = ue.get_process_from_json_folder('../../test', 'ice_sim', 'snow_sim')

KeyError: 'single data'

In [13]:
sim_proc.ice_dz_history

array([[0.19047619, 0.18095238, 0.17142857, 0.16190476, 0.15238095,
        0.14285714, 0.13333333, 0.12380952, 0.11428571, 0.1047619 ,
        0.0952381 , 0.08571429, 0.07619048, 0.06666667, 0.05714286,
        0.04761905, 0.03809524, 0.02857143, 0.01904762, 0.00952381],
       [0.19049469, 0.18096995, 0.17144522, 0.16192048, 0.15239575,
        0.14287102, 0.13334628, 0.12382155, 0.11429681, 0.10477208,
        0.09524734, 0.08572261, 0.07619787, 0.06667314, 0.05714841,
        0.04762367, 0.03809894, 0.0285742 , 0.01904947, 0.00952473],
       [0.19051318, 0.18098752, 0.17146186, 0.1619362 , 0.15241054,
        0.14288489, 0.13335923, 0.12383357, 0.11430791, 0.10478225,
        0.09525659, 0.08573093, 0.07620527, 0.06667961, 0.05715395,
        0.0476283 , 0.03810264, 0.02857698, 0.01905132, 0.00952566],
       [0.19053167, 0.18100508, 0.1714785 , 0.16195192, 0.15242533,
        0.14289875, 0.13337217, 0.12384558, 0.114319  , 0.10479242,
        0.09526583, 0.08573925, 0.07621267, 0

In [14]:
process_sim.ice_dz_history

array([[0.097, 0.097, 0.097, 0.097, 0.097, 0.097, 0.097, 0.097, 0.097,
        0.097, 0.097, 0.097, 0.097, 0.097, 0.097, 0.097, 0.097, 0.097,
        0.097, 0.097],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
          nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
          nan,   nan],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
          nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
          nan,   nan],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
          nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
          nan,   nan],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
          nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
          nan,   nan],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
          nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
          nan,   nan],
       [  

In [3]:
with open("Validation/12-levels.dat") as file:
    Z = [float(z.replace(' ', '')[:-1]) for z in file.readlines()]

In [4]:
data = pd.read_csv('Validation/full_data.csv')

In [ ]:
data.columns

In [ ]:
prec = 5.
cmap_base = plt.get_cmap('rainbow')
vmin = data.loc[:, 'T_1':'T_50'].values.min()
vmax = data.loc[:, 'T_1':'T_50'].values.max()

boundaries = np.concatenate(([vmin], np.arange(np.floor(vmin + prec), vmax, prec), [vmax]))
centers = (boundaries[1:] + boundaries[:-1])/2
centers_scaled = (centers - vmin) / (vmax - vmin)

cmap_custom = clr.ListedColormap([cmap_base(x) for x in centers_scaled])
norm_custom = clr.BoundaryNorm(boundaries, cmap_custom.N)

In [ ]:
plt.figure(figsize=(20, 10))
plt.imshow(data.loc[:, 'T_1':'T_50'].T,
           aspect='auto', cmap=cmap_custom, norm=norm_custom,
           extent=[data.loc[0, 'jday'], data.loc[data.index[-1], 'jday'], Z[-1], Z[0]])
plt.plot(data['jday'], data['hs_level'], color='white', lw=3, ls=':', label='snow surface')
plt.plot(data['jday'], data['hf_level'], color='white', lw=3, ls='--', label='snow-ice interface')
plt.plot(data['jday'], data['hi_level'], color='white', lw=3, label='ice base')
plt.plot(data['jday'], data['hs_best'], color='black', lw=3, ls=':', label='snow surface best')
plt.xticks(size=15)
plt.yticks(size=15)
plt.legend(loc='lower left', facecolor='black', labelcolor='white', prop={'size': 20})
plt.colorbar(ticks=boundaries)
# plt.savefig('test-image.png', dpi=150)
plt.show()

Судя по статье (Fig.5 (a), (b)), чёрные точки - это метод приближения, использованный в статье Хувальда

In [5]:
# sigma mesh
dsigma_ice = np.full(20, 1.0/20)
dsigma_snow = np.full(5, 1.0/5)

In [6]:
# init state from data
T_ice_init, T_snow_init, Toi_init, Tis_init, Tsa_init, \
dzi_init, dzs_init = ue.get_init_from_data(data, Z, dsigma_ice, dsigma_snow)

# time_arr = ((data['jday'] - data.loc[0, 'jday'])*24*3600).values
time_arr = data['jday'].values

In [ ]:
# process from data
process_data = ue.process_from_data(Z,
                                    data.loc[:, 'T_1':'T_50'].values, 
                                    data['Tib_interp'].values, data['Tis_interp'].values,
                                    data['Tss'].values,
                                    data['hi_best'].values, data['hf_best'].values,
                                    data['hs_best'].values,
                                    np.ones(20)/20.0, np.ones(5)/5.0,
                                    time_arr, ue.rho_i)

In [7]:
# forcing
e_s = lambda T: 6.11*np.exp(ue.c1_i*T/(T + ue.T0 - ue.c2_i))
q_surf = lambda T: 0.622*e_s(T)/(ue.P_surf - 0.378*e_s(T))

albe = data['albe'].values
Tib_interp = data['Tib_interp'].values
tair = data['tair'].values
uair = data['uair'].values
qair = data['qair'].values
prec = data['prec_eff'].values
swdo = data['swdo'].values
lwdo = data['lwdo'].values
focn_pit = data['focn_pit'].values
Focn_y = data['Focn_y'].values


find_index_fast = lambda time_sec: np.searchsorted(time_arr, time_sec, side='right') - 1
albedo = lambda time: albe[find_index_fast(time)]
Toi = lambda time: Tib_interp[find_index_fast(time)]
T_a = lambda time: tair[find_index_fast(time)] - ue.T0
u_a = lambda time: uair[find_index_fast(time)]
q_a = lambda time: qair[find_index_fast(time)] * 1e-3
p = lambda time: prec[find_index_fast(time)] * ue.mmd_to_ms
F_sw = lambda time: swdo[find_index_fast(time)]
F_lw = lambda time: lwdo[find_index_fast(time)]
F_bolz = lambda T: -ue.sigma*(T + ue.T0)**4
F_sh = lambda T, time: ue.rho_a*ue.c_pa*ue.C_sh*u_a(time)*(T_a(time) - T)
F_lh = lambda T, time: ue.rho_a*ue.L_s0*ue.C_lh*u_a(time)*(q_a(time) - q_surf(T))
F_P = lambda T, time: p(time)*ue.rho_w*ue.c_pw*max(T_a(time) - T, 0)
F_atm = lambda T, time, i_0: ue.emissivity*(F_lw(time) + F_bolz(T)) \
                           + (1 - albedo(time))*(1 - i_0)*F_sw(time) \
                           + F_sh(T, time) + F_P(T, time) + F_lh(T, time) 

F_atm_ice = lambda T, time: F_atm(T, time, ue.i0_i)
F_atm_snow = lambda T, time: F_atm(T, time, ue.i0_s)
F_ocn = lambda T, time: Focn_y[find_index_fast(time)]

In [8]:
%%time
process_sim = ue.main_process \
(
    time_step=3600.0,
    time_end=10*3600.0,
    N_pseudoiter=50,
    Ti_init=T_ice_init,
    Ts_init=T_snow_init,
    Tis_init=Tis_init,
    Tsa_init=Tsa_init,
    dzi_init=dzi_init,
    dzs_init=dzs_init,
    salinity=np.linspace(4.0, 1.0, len(dzi_init)),
    snow_thickness_threshold=0.01,
    Toi=Toi,
    Ta=T_a,
    p=p,
    F_atm_ice=F_atm_ice,
    F_atm_snow=F_atm_snow,
    F_sw=F_sw,
    F_ocn=F_ocn#,
#     json_output_folder='../../test',
#     json_ice_prefix='ice_sim',
#     json_snow_prefix='snow_sim'
)

Time 1.0 h.: Snow-ice freezing...
Time 2.0 h.: Snow-ice freezing...
Time 3.0 h.: Snow-ice freezing...
Time 3.0 h.: Snow-ice melting...
Time 4.0 h.: Snow-ice freezing...
Time 4.0 h.: Snow-ice melting...
Time 5.0 h.: Snow-ice freezing...
Time 5.0 h.: Snow-ice melting...
Time 6.0 h.: Snow-ice freezing...
Time 6.0 h.: Snow-ice melting...
Time 7.0 h.: Snow-ice freezing...
Time 7.0 h.: Snow-ice melting...
Time 8.0 h.: Snow-ice freezing...
Time 8.0 h.: Snow-ice melting...
Time 9.0 h.: Snow-ice freezing...
Time 9.0 h.: Snow-ice melting...
Time 10.0 h.: Snow-ice freezing...
Time 10.0 h.: Snow-ice melting...
CPU times: user 1.2 s, sys: 7.83 ms, total: 1.21 s
Wall time: 1.23 s


In [9]:
process_sim.ice_temp_history

array([[ -1.517 ,  -1.733 ,  -2.315 ,  -2.897 ,  -3.479 ,  -4.1545,
         -4.8335,  -5.5125,  -6.1915,  -6.789 ,  -7.6065,  -8.253 ,
         -8.9075,  -9.5865, -10.2655, -11.054 , -11.784 , -12.875 ,
        -14.563 , -16.8   ],
       [     nan,      nan,      nan,      nan,      nan,      nan,
             nan,      nan,      nan,      nan,      nan,      nan,
             nan,      nan,      nan,      nan,      nan,      nan,
             nan,      nan],
       [     nan,      nan,      nan,      nan,      nan,      nan,
             nan,      nan,      nan,      nan,      nan,      nan,
             nan,      nan,      nan,      nan,      nan,      nan,
             nan,      nan],
       [     nan,      nan,      nan,      nan,      nan,      nan,
             nan,      nan,      nan,      nan,      nan,      nan,
             nan,      nan,      nan,      nan,      nan,      nan,
             nan,      nan],
       [     nan,      nan,      nan,      nan,      nan,      nan,


In [ ]:
process_sim.ice_dz_history

In [ ]:
test_anim = uv.animate([process_sim[:1000], process_data[:1000]], interval=100, savepath='test.mp4')

In [ ]:
test_anim#.save('test.mp4')

In [ ]:
out = uv.timeseries_img(process_data, y_points=250)#, savepath='timeseries.png')

In [ ]:
uv.timeseries_img(process_data, y_points=200, mode='month',
                  cmap_ice='RdBu_r', tmin_ice=-25, tmax_ice=0, step_ice=2.0,
                  cmap_snow='PuOr_r', tmin_snow=-40, tmax_snow=0, step_snow=2.0,
                  color_waterline='green', savepath='media/data_SHEBA.png')

In [ ]:
uv.timeseries_err(process_sim, process_data, x_ticks=20, y_ticks=10)

In [ ]:
uv.timeseries_err(process_sim, process_data, mode='month', x_ticks=20, y_ticks=10)

In [ ]:
uv.timeseries_err(process_sim, process_data, tmin_err=-4., tmax_err=4., step_err=1.)

In [ ]:
uv.timeseries_err(process_sim[5000:6500], process_data[5000:6500], tmin_err=-4., step_err=.5)

In [ ]:
uv.timeseries_err(process_sim, process_data, x_ticks=20, y_ticks=10,
                  label_data='SHEBA', legend_loc='lower right')

In [ ]:
k_unter = lambda T, S: 2.03 + 0.1172*S/T

In [ ]:
T = np.linspace(-30, -0.1, 100)

plt.figure(figsize=(15, 10))
# plt.title('Different thermal conductivity parametrizations, S = 2', size=20) 
plt.plot(T, [ue.k_i(t, 2) for t in T], label='"bubbly-brine"', lw=5)
plt.plot(T, k_unter(T, 2), label='Untersteiner', lw=5)
plt.xlabel(r'Temperature, $^o$C', size=25)
plt.ylabel(r'Thermal conductivity, W m$^{-1}$ K$^{-1}$', size=25)
plt.tick_params(labelsize=17)
plt.legend(prop={'size': 30}, loc='lower left')
plt.grid(ls='--')
plt.tight_layout()
plt.savefig('media/Untersteiner_vs_BB.png', dpi=200)
plt.show()